using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Controls.Primitives;
using static MO2ExportImport.FormatHandler;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace MO2ExportImport
{
    public class CommonFuncs
    {
        public static List<ModListing> LoadModList(string filePath, bool reverseOrder = true)
        {
            if (!File.Exists(filePath))
            {
                return new ();
            }

            var lines = File.ReadAllLines(filePath).Where(line => !line.StartsWith("#")).ToList();
            var modListings = new List<ModListing>();

            foreach (var line in lines)
            {
                modListings.Add(new(line));
            }

            if (reverseOrder)
            {
                modListings.Reverse(); // Reverse the list in place if needed
            }

            return modListings;
        }

        public static bool SaveModList(string filePath, List<ModListing> modList, out string exceptionStr)
        {
            List<string> output = modList.Select(mod => mod.GetCurrentEntryString()).ToList();
            
            // Reverse the ProfileModList back to original order before saving
            output.Reverse();
            
            // Reinsert the special comment line at the beginning
            output.Insert(0, "# This file was automatically generated by Mod Organizer.");

            // Save the edited mod list
            try
            {
                File.WriteAllLines(filePath, output);
                exceptionStr = string.Empty;
                return true;
            }
            catch (Exception e)
            {
                exceptionStr = $"Could not save profile information at {filePath}. Error:" + Environment.NewLine + e.Message;
                return false;
            }
        }

        public static bool SavePluginList(string filePath, List<PluginListing> pluginList, bool asLoadOrderFile, out string exceptionStr)
        {
            var outputPluginList = pluginList;
            if (!asLoadOrderFile)
            {
                outputPluginList = pluginList.Where(x => !x.IsBaseGamePlugin).ToList();
            }
            var output = outputPluginList
                .Select(x => x.GetCurrentEntryString())
                .ToList();

            if (asLoadOrderFile) // loadorder.txt doesn't have activation status symbol
            {
                output = output.Select(x => FormatHandler.TrimPluginActivationStatus(x)).ToList();
            }
            
            output.Insert(0, "# This file was automatically generated by Mod Organizer.");

            // Save the edited plugin lists
            try
            {
                File.WriteAllLines(filePath, output);
                exceptionStr = string.Empty;
            }
            catch (Exception e)
            {
                exceptionStr = $"Could not save profile information at {filePath}. Error:" + Environment.NewLine + e.Message;
                return false;
            }

            if (pluginList.Any(x => x.PluginGroup is not null))
            {
                var dir = Path.GetDirectoryName(filePath);
                var pluginGroupsPath = Path.Combine(dir, "plugingroups.txt");

                if (!SavePluginGroups(pluginGroupsPath, pluginList, out var groupsExceptionStr))
                {
                    exceptionStr += Environment.NewLine + groupsExceptionStr;
                    return false;
                }
            }
            
            return true;
        }

        public static List<PluginListing> LoadPluginListFromLoadOrder(string dirPath, bool reverseOrder = false, bool fallThroughToRaw = true)
        {
            var pluginListings = new List<PluginListing>();
            
            var pluginsPath = Path.Combine(dirPath, "plugins.txt");
            var loadOrderPath = Path.Combine(dirPath, "loadorder.txt");
            var pluginGroupsPath = Path.Combine(dirPath, "pluginGoups.txt");

            var rawPlugins = LoadPluginListRaw(pluginsPath, reverseOrder);
            
            if (!File.Exists(loadOrderPath) && fallThroughToRaw)
            {
                return rawPlugins;
            }
            
            var pluginGroups = LoadPluginGroups(pluginGroupsPath);
            
            var lines = File.ReadAllLines(loadOrderPath).Where(line => !line.StartsWith("#")).ToList();
            
            if (reverseOrder)
            {
                lines.Reverse(); // Reverse the list in place if needed
            }

            foreach (var line in lines)
            {
                var rawEntry = rawPlugins.Where(x => x.Name == line).FirstOrDefault();
                if (rawEntry is null)
                {
                    var entry = new PluginListing(line, true);
                    entry.PluginGroup = pluginGroups.ContainsKey(entry.Name) ? pluginGroups[entry.Name] : null;
                    entry.IsBaseGamePlugin = true;
                    entry.Enabled = true;
                    pluginListings.Add(entry);
                }
                else
                {
                    pluginListings.Add(rawEntry);   
                }
            }
            return pluginListings;
        }

        public static List<PluginListing> LoadPluginListRaw(string filePath, bool reverseOrder = false)
        {
            var pluginListings = new List<PluginListing>();
            
            var dir = Path.GetDirectoryName(filePath);
            var pluginGroupsPath = Path.Combine(dir, "plugingroups.txt");
            
            var pluginGroups = LoadPluginGroups(pluginGroupsPath);
            
            if (!File.Exists(filePath))
            {
                return pluginListings;
            }

            var lines = File.ReadAllLines(filePath).Where(line => !line.StartsWith("#")).ToList();

            if (reverseOrder)
            {
                lines.Reverse(); // Reverse the list in place if needed
            }

            foreach (var line in lines)
            {
                var entry = new PluginListing(line);
                entry.PluginGroup = pluginGroups.ContainsKey(entry.Name) ? pluginGroups[entry.Name] : null;
                pluginListings.Add(entry);
            }

            return pluginListings;
        }

        public static bool SavePluginGroups(string filePath, List<PluginListing> pluginListings, out string exceptionStr)
        {
            var output = pluginListings.
                Select(x => string.Join('|',x.Name, x.PluginGroup))
                .OrderBy(x => x.ToLower())
                .ToList();
            
            output.Insert(0, "# This file was automatically generated by Mod Organizer.");

            // Save the edited plugin lists
            try
            {
                File.WriteAllLines(filePath, output);
                exceptionStr = string.Empty;
                return true;
            }
            catch (Exception e)
            {
                exceptionStr = $"Could not save plugin groups at {filePath}. Error:" + Environment.NewLine + e.Message;
                return false;
            }
        }
        
        public static Dictionary<string, string> LoadPluginGroups(string filePath)
        {
            List<string> notifications = new();
            var pluginGroups = new Dictionary<string, string>();
            
            if (!File.Exists(filePath))
            {
                return pluginGroups;
            }

            var lines = File.ReadAllLines(filePath).Where(line => !line.StartsWith("#")).ToList();

            foreach (var line in lines)
            {
                var split= line.Split('|').ToList();
                if (split.Count >= 2)
                {
                    var pluginGroup = split.Last();
                    split.RemoveAt(split.Count - 1); 
                    var pluginName = string.Join("|", split);
                    if (pluginGroups.ContainsKey(pluginName))
                    {
                        notifications.Add($"Warning: {pluginName} appears more than once in {filePath}");
                    }
                    else
                    {
                        pluginGroups.Add(pluginName, pluginGroup); 
                    }
                }
            }

            if (notifications.Any())
            {
                ScrollableMessageBox.Show(notifications, "Warning");
            }
            
            return pluginGroups;
        }

        public static bool IsNoDelete(string modName, out string matchedPrefix)
        {
            matchedPrefix = string.Empty;
            
            // Define a case-insensitive regex pattern
            string pattern = @"^\[NoDelete.*?\]";

            // Match the pattern at the start of the string
        
            var match = Regex.Match(modName, pattern, RegexOptions.IgnoreCase);

            // Check if a match is found at the start of the string
            if (match.Success && match.Index == 0)
            {
                matchedPrefix = match.Value;
                return true;
            }
            return false;
        }
        
        public static string RemoveNoDeletePrefix(string modName) // expects mod name without the activation status
        {
            if (IsNoDelete(modName, out string matchedPrefix))
            {
                // Remove the matched substring and trim the result
                modName =  modName.Substring(matchedPrefix.Length).Trim();
                return modName;
            }

            // Return the original string if no match
            return modName;
        }

        public static List<string> GetPluginPathsInDir(string dirPath)
        {
            if (!Directory.Exists(dirPath))
            {
                return new();
            }

            return Directory.GetFiles(dirPath, "*.*", SearchOption.TopDirectoryOnly)
                                           .Where(f => f.EndsWith(".esp", StringComparison.OrdinalIgnoreCase) ||
                                                       f.EndsWith(".esm", StringComparison.OrdinalIgnoreCase) ||
                                                       f.EndsWith(".esl", StringComparison.OrdinalIgnoreCase))
                                           .ToList();
        }

        public static List<string> GetPluginNamesInDir(string dirPath, bool withExtension = true)
        {
            List<string> pluginNames = new();
            var paths = GetPluginPathsInDir(dirPath);
            foreach (var path in paths)
            {
                if (withExtension)
                {
                    pluginNames.Add(Path.GetFileName(path));
                }
                else
                {
                    pluginNames.Add(Path.GetFileNameWithoutExtension(path));  
                }
            }
            
            return pluginNames;
        }

        public static string AddEntryInSplicedMode(List<IListing> profileList, List<IListing> sourceList, IListing currentEntry, List<IListing> ignoredEntries, StringType stringType, List<string> eventLog)
        {
            for (int i = currentEntry.GetIndexOf(sourceList) - 1; i >= 0; i--)
            {
                var precedingSearchEntry = sourceList[i];

                eventLog.Add("Attempting to place " + currentEntry.Name + " after " + precedingSearchEntry.Name);

                if (ignoredEntries.Any(x => x.Equals(precedingSearchEntry)))
                {
                    eventLog.Add("The position of " + precedingSearchEntry.Name + " is to be ignored during splicing. Continuing to next preceding entry");
                    continue;
                }

                int indexInProfile = precedingSearchEntry.GetIndexOf(profileList);
                if (indexInProfile != -1)
                {
                    eventLog.Add("Success: Inserting " + currentEntry.Name + " at position " + (indexInProfile+1).ToString());
                    profileList.Insert(indexInProfile + 1, currentEntry);
                    return precedingSearchEntry.Name;
                }
            }

            // If no precedingEntry is found or inserted, add to end
            eventLog.Add("Exhausted all preceding entries in the source list for " + currentEntry.Name + ". Adding to the end of the destination list.");
            profileList.Add(currentEntry);
            //ignoredEntries.Add(currentEntry); Commented out for now. Double checking my logic, I don't think this makes sense to include.
            return "end";
        }
        
        // Add to CommonFuncs.cs:

        public static string GetSelectedProfileFromIni(string mo2Directory)
        {
            var iniPath = Path.Combine(mo2Directory, "ModOrganizer.ini");
    
            if (!File.Exists(iniPath))
            {
                return null;
            }

            try
            {
                var lines = File.ReadAllLines(iniPath);
                foreach (var line in lines)
                {
                    if (line.StartsWith("selected_profile=", StringComparison.OrdinalIgnoreCase))
                    {
                        // Format is: selected_profile=@ByteArray(Profile Name)
                        var match = Regex.Match(line, @"@ByteArray\((.+?)\)");
                        if (match.Success && match.Groups.Count > 1)
                        {
                            return match.Groups[1].Value;
                        }
                    }
                }
            }
            catch (Exception)
            {
                // If there's any error reading the file, return null to fall back to first profile
                return null;
            }

            return null;
        }
        
        // Add these methods to CommonFuncs class

        private static string GetMO2FolderFromIni(string mo2Directory, string iniKey, string defaultSubfolder)
        {
            var iniPath = Path.Combine(mo2Directory, "ModOrganizer.ini");

            if (!File.Exists(iniPath))
            {
                // If INI doesn't exist, fall back to default subfolder
                var defaultPath = Path.Combine(mo2Directory, defaultSubfolder);
                return defaultPath;
            }

            var lines = File.ReadAllLines(iniPath);

            foreach (var line in lines)
            {
                if (line.StartsWith($"{iniKey}=", StringComparison.OrdinalIgnoreCase))
                {
                    var folderPath = line.Substring($"{iniKey}=".Length).Trim();

                    // Handle relative paths
                    if (!Path.IsPathRooted(folderPath))
                    {
                        folderPath = Path.Combine(mo2Directory, folderPath);
                    }

                    return folderPath;
                }
            }

            // If no line exists for this key, fall back to default subfolder
            var defaultDir = Path.Combine(mo2Directory, defaultSubfolder);
            return defaultDir;
        }

        public static string GetModsDirectory(string mo2Directory)
        {
            return GetMO2FolderFromIni(mo2Directory, "mod_directory", "mods");
        }

        public static string GetProfilesDirectory(string mo2Directory)
        {
            return GetMO2FolderFromIni(mo2Directory, "profiles_directory", "profiles");
        }

        public static string GetDownloadsDirectory(string mo2Directory)
        {
            return GetMO2FolderFromIni(mo2Directory, "download_directory", "downloads");
        }

        public static string GetOverwriteDirectory(string mo2Directory)
        {
            return GetMO2FolderFromIni(mo2Directory, "overwrite_directory", "overwrite");
        }
    }
}
