using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Controls.Primitives;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace MO2ExportImport
{
    public class CommonFuncs
    {
        public static List<ModListing> LoadModList(string filePath, bool reverseOrder = true)
        {
            if (!File.Exists(filePath))
            {
                return new ();
            }

            var lines = File.ReadAllLines(filePath).Where(line => !line.StartsWith("#")).ToList();
            var modListings = new List<ModListing>();

            foreach (var line in lines)
            {
                modListings.Add(new(line));
            }

            if (reverseOrder)
            {
                modListings.Reverse(); // Reverse the list in place if needed
            }

            return modListings;
        }

        public static bool SaveModList(string filePath, List<ModListing> modList, out string exceptionStr)
        {
            List<string> output = modList.Select(mod => mod.GetCurrentEntryString()).ToList();
            
            // Reverse the ProfileModList back to original order before saving
            output.Reverse();
            
            // Reinsert the special comment line at the beginning
            output.Insert(0, "# This file was automatically generated by Mod Organizer.");

            // Save the edited mod list
            try
            {
                File.WriteAllLines(filePath, output);
                exceptionStr = string.Empty;
                return true;
            }
            catch (Exception e)
            {
                exceptionStr = $"Could not save profile information at {filePath}. Error:" + Environment.NewLine + e.Message;
                return false;
            }
        }

        public static bool SavePluginList(string filePath, List<PluginListing> pluginList, out string exceptionStr)
        {
            var output = pluginList.Select(x => x.GetCurrentEntryString()).ToList();
            
            output.Insert(0, "# This file was automatically generated by Mod Organizer.");

            // Save the edited plugin lists
            try
            {
                File.WriteAllLines(filePath, output);
                exceptionStr = string.Empty;
                return true;
            }
            catch (Exception e)
            {
                exceptionStr = $"Could not save profile information at {filePath}. Error:" + Environment.NewLine + e.Message;
                return false;
            }
        }


        public static List<PluginListing> LoadPluginList(string filePath, bool reverseOrder = false)
        {
            var pluginListings = new List<PluginListing>();
            
            if (!File.Exists(filePath))
            {
                return pluginListings;
            }

            var lines = File.ReadAllLines(filePath).Where(line => !line.StartsWith("#")).ToList();

            if (reverseOrder)
            {
                lines.Reverse(); // Reverse the list in place if needed
            }

            foreach (var line in lines)
            {
                pluginListings.Add(new(line));
            }

            return pluginListings;
        }

        public static bool IsNoDelete(string modName, out string matchedPrefix)
        {
            matchedPrefix = string.Empty;
            
            // Define a case-insensitive regex pattern
            string pattern = @"^\[NoDelete.*?\]";

            // Match the pattern at the start of the string
        
            var match = Regex.Match(modName, pattern, RegexOptions.IgnoreCase);

            // Check if a match is found at the start of the string
            if (match.Success && match.Index == 0)
            {
                matchedPrefix = match.Value;
                return true;
            }
            return false;
        }
        
        public static string RemoveNoDeletePrefix(string modName) // expects mod name without the activation status
        {
            if (IsNoDelete(modName, out string matchedPrefix))
            {
                // Remove the matched substring and trim the result
                modName =  modName.Substring(matchedPrefix.Length).Trim();
                return modName;
            }

            // Return the original string if no match
            return modName;
        }
    }
}
