name: Publish

on:
  release:
    types: [published]
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.*
    - name: Install dependencies
      run: dotnet restore MO2ExportImport.sln
      
    - name: Build
      run: dotnet build MO2ExportImport.sln -c Release --no-restore
      
    - name: Test
      run: dotnet test MO2ExportImport.sln -c Release --no-build
      
    - name: Publish
      run: dotnet publish MO2ExportImport.csproj --configuration Release -p:PublishSingleFile=false
      
    - name: Archive Release
      run: |
        powershell Compress-Archive MO2ExportImport/bin/Release/net8.0-windows/publish/* "MO2ExportImport_${{ github.event.release.tag_name }}.zip"
    - name: Publish MO2ExportImport to Github
      uses: svenstaro/upload-release-action@v2
      with:
        file: "MO2_Splicer_${{ github.event.release.tag_name }}.zip"
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.release.tag_name }}
